### ISSUE TITLE
getAllVersions not working

### ISSUE THREAD

**Issue by openam** [DavidTanner/nodecredstash#15]
The [example](https://github.com/DavidTanner/nodecredstash#getallversionsname-limit-cb) in the docs refers to `getAllSecrets` instead of `getAllVersions`.

I'm getting the following error when running `credstash.getAllVersions({name: 'test'})`:
```
     TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
      at Function.Buffer.from (buffer.js:161:9)
      at new Buffer (buffer.js:131:17)
      at Object.b64decode (node_modules/nodecredstash/js/lib/utils.js:43:12)
      at Credstash.decryptStash (node_modules/nodecredstash/js/index.js:149:25)
      at Credstash.credstash.(anonymous function) [as decryptStash] (node_modules/nodecredstash/js/index.js:40:25)
      at results.Items.map.stash (node_modules/nodecredstash/js/index.js:182:18)
      at Array.map (native)
      at ddb.getAllVersions.then (node_modules/nodecredstash/js/index.js:181:49)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:208:7)
```

**Comment by atif** [comment]
Facing the same issue

**Comment by atif** [comment]
^ @DavidTanner

**Comment by DavidTanner** [comment]
Please check with v1.1.1
